---
output:
  html_document: default
  h1 text-align: center
---

# BIOL3360: Analysis and Communication of Biological Data{#chap1}

## Course description

As scientists, we need to be able to collect, analyse and interpret data in terms of statistical and mathematical models. We also need to be able to __communicate__ our findings to other scientists, grant funding bodies, government departments and the general public. This course is designed to give you these skills. We intend that the skills you gain in this course will serve you well in your future careers and studies in biology, or indeed any other field of science.

## Course Delivery

The course is designed with three ``modules:`` Statistical Modelling, Dynamic Modelling and Communication. Statistical Modelling is taught by Simone Blomberg before the mid-semester break. The first three weeks are devoted to gaining R programming skills (no statistics taught in these weeks). Dynamic Modelling is taught by Jan Engelstaedter after the mid-semester break, and the Communication module is run for the entire semester by Louise Kuchel.

The course is structured into two ``workshops,`` one two-hour and one three hour, for a total of 5 contact hours during the week. We expect you to spend another 5 hours on the content outside of contact hours.

## Textbooks and Resources

The textbook for R programming will be, [The Art of R Programming](https://search-ebscohost-com.ezproxy.library.uq.edu.au/login.aspx?direct=true&db=nlebk&AN=440016&site=ehost-live) by Matloff. This is a good introduction which emphasises good programming habits. We will work through several chapters.

There is no set textbook for the Statistical Modelling module. However, there are many books which cover the material. My (Simone's) favorites are:

- [Mixed-Effects Modelling in S and S-PLUS](https://ebookcentral-proquest-com.ezproxy.library.uq.edu.au/lib/uql/detail.action?docID=1204538)
- [Generalized Linear Models](https://search.library.uq.edu.au/permalink/f/12kerkf/61UQ_ALMA2179625110003131)

These books will cover the theory. We will discuss the theory and work through examples in R in the workshops.

## Assessment

There will be fortnightly quizzes throughout the course, and one ``practical`` exam for the communication module. There are no mid-semester or final exams.


## Goals and expectations

- The course can be completed to a high level, if you work diligently. We expect you to come to the workshops (which will not necessarily be recorded). 

- We expect you to prepare for each quiz. We expect you to use your initiative, intelligence, self-discipline, curiosity and vested interest to take responsibility for your own learning. If you start to have trouble, we expect you to ask for help from us, to get you back on track. 

- Feel free to contact any of us by email, but do so sparingly, and be courteous and polite.

- Ask questions (publicly, privately, anonymously) if you don't understand a concept.

- If we can improve something about our teaching or the course, let us know early because we will fix it if we can (SECaTs are good for us and for students next year, but they occur too late to benefit you).

- If you have a problem, let us know early and propose a solution if possible.

## Course communication

We will provide an Ed Discussion Board where you can ask questions of us, and your fellow students, anonymously if need be. Feel free to make an appointment to meet us personally outside of the workshops. We are happy to provide face-to-face advice.

Our email addresses are: \
Simone [s.blomberg1\@uq.edu.au](mailto:s.blomberg1@uq.edu.au){.email} \
Jan [j.engelstaedter\@uq.edu.au](mailto:j.engelstaedter@uq.edu.au){.email} \
Louise [l.kuchel\@uq.edu.au](mailto:l.kuchel@uq.edu.au){.email}

## And finally...

Good luck with the course! We hope you enjoy it!

Simone Blomberg.
