---
output:
  html_document: default
---

# Beginning R Programming {#chap3}

## The Workspace Setup

Obtain R from the [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/) and install it in the usual way that you install other software. You can use R from the command line in a terminal by typing R (Mac and Linux) or by clicking on the R icon (Windows). However, using R in this way is usually quite tortuous. It is much better to use an Interactive Development Environment (IDE). We shall use RStudio as our IDE. Download and install RStudio from the [Posit](https://posit.co/) web site. Make sure you install the free version. After installation, start it up in the usual way for your system. An important point to note: __RStudio is not R!__. RStudio is merely an interface to R. You should normally not need to cite RStudio in reports etc. Just cite R. To cite R, type ``citation()`` at the R prompt. It will output a citation that you can paste into your reports.

Open RStudio by clicking on the RStudio icon. A window should pop up with three panes. The pane on the left is the R console. This is where R output will appear. You can also type commands right in there. Minimise the R console and you should see another pane: This is the source pane. You can open new R documents there and edit your code. Make sure you save your code with the extension ``.R``. That will allow RStudio to recognise your R file and give you text coloration and other goodies. The two panes on the left hand side of the window include facilities for examining your workspace environment, viewing plots and help files and a number of other things. Now we are ready to start programming.

## First steps

Go to the top-left pane and type. 

```{r, eval=FALSE}
cat("Hello World!")
```

Press the ``run`` button at the top right of the pane. You should see the output come out in the Console pane. Congratulations! This is your first R program. A "Hello World" program is traditionally the first program a new programmer writes on a new system that they are learning. You have joined the ranks of computer programmers!


Go to ``The Art of R Programming`` and read through the text up to page 