<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Multinomial Experiments | BIOL3360</title>
  <meta name="description" content="10 Multinomial Experiments | BIOL3360" />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Multinomial Experiments | BIOL3360" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Multinomial Experiments | BIOL3360" />
  
  
  

<meta name="author" content="Simone Blomberg" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap9.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link rel="shortcut icon" href="pics/favicon.ico">


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://shire.science.uq.edu.au/QBIOL/">QBIO Home</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to BIOL3360!</a></li>
<li class="chapter" data-level="1" data-path="chap1.html"><a href="chap1.html"><i class="fa fa-check"></i><b>1</b> BIOL3360: Analysis and Communication of Biological Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chap1.html"><a href="chap1.html#course-description"><i class="fa fa-check"></i><b>1.1</b> Course description</a></li>
<li class="chapter" data-level="1.2" data-path="chap1.html"><a href="chap1.html#course-delivery"><i class="fa fa-check"></i><b>1.2</b> Course Delivery</a></li>
<li class="chapter" data-level="1.3" data-path="chap1.html"><a href="chap1.html#textbooks-and-resources"><i class="fa fa-check"></i><b>1.3</b> Textbooks and Resources</a></li>
<li class="chapter" data-level="1.4" data-path="chap1.html"><a href="chap1.html#assessment"><i class="fa fa-check"></i><b>1.4</b> Assessment</a></li>
<li class="chapter" data-level="1.5" data-path="chap1.html"><a href="chap1.html#goals-and-expectations"><i class="fa fa-check"></i><b>1.5</b> Goals and expectations</a></li>
<li class="chapter" data-level="1.6" data-path="chap1.html"><a href="chap1.html#course-communication"><i class="fa fa-check"></i><b>1.6</b> Course communication</a></li>
<li class="chapter" data-level="1.7" data-path="chap1.html"><a href="chap1.html#and-finally"><i class="fa fa-check"></i><b>1.7</b> And finally…</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap2.html"><a href="chap2.html"><i class="fa fa-check"></i><b>2</b> Week 1: R Programming I</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap2.html"><a href="chap2.html#why-programming-why-statistics-why-r"><i class="fa fa-check"></i><b>2.1</b> Why Programming? Why Statistics? Why R?</a></li>
<li class="chapter" data-level="2.2" data-path="chap2.html"><a href="chap2.html#why-statistics"><i class="fa fa-check"></i><b>2.2</b> Why Statistics?</a></li>
<li class="chapter" data-level="2.3" data-path="chap2.html"><a href="chap2.html#why-r"><i class="fa fa-check"></i><b>2.3</b> Why R?</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap3.html"><a href="chap3.html"><i class="fa fa-check"></i><b>3</b> Beginning R Programming</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap3.html"><a href="chap3.html#the-workspace-setup"><i class="fa fa-check"></i><b>3.1</b> The Workspace Setup</a></li>
<li class="chapter" data-level="3.2" data-path="chap3.html"><a href="chap3.html#first-steps"><i class="fa fa-check"></i><b>3.2</b> First steps</a></li>
<li class="chapter" data-level="3.3" data-path="chap3.html"><a href="chap3.html#the-art-of-r-programming"><i class="fa fa-check"></i><b>3.3</b> The Art of R Programming</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap4.html"><a href="chap4.html"><i class="fa fa-check"></i><b>4</b> More R Programming</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap4.html"><a href="chap4.html#data-structures"><i class="fa fa-check"></i><b>4.1</b> Data Structures</a></li>
<li class="chapter" data-level="4.2" data-path="chap4.html"><a href="chap4.html#lists"><i class="fa fa-check"></i><b>4.2</b> Lists</a></li>
<li class="chapter" data-level="4.3" data-path="chap4.html"><a href="chap4.html#data-frames"><i class="fa fa-check"></i><b>4.3</b> Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap5.html"><a href="chap5.html"><i class="fa fa-check"></i><b>5</b> Flow of Control</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap5.html"><a href="chap5.html#loops"><i class="fa fa-check"></i><b>5.1</b> Loops</a></li>
<li class="chapter" data-level="5.2" data-path="chap5.html"><a href="chap5.html#for-loops"><i class="fa fa-check"></i><b>5.2</b> For loops</a></li>
<li class="chapter" data-level="5.3" data-path="chap5.html"><a href="chap5.html#while-and-repeat"><i class="fa fa-check"></i><b>5.3</b> while and repeat</a></li>
<li class="chapter" data-level="5.4" data-path="chap5.html"><a href="chap5.html#branching-code-the-if-then-else-construct."><i class="fa fa-check"></i><b>5.4</b> Branching code: The if-then-else construct.</a></li>
<li class="chapter" data-level="5.5" data-path="chap5.html"><a href="chap5.html#conclusion"><i class="fa fa-check"></i><b>5.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap6.html"><a href="chap6.html"><i class="fa fa-check"></i><b>6</b> Experimental Design</a>
<ul>
<li class="chapter" data-level="6.1" data-path="chap6.html"><a href="chap6.html#some-history"><i class="fa fa-check"></i><b>6.1</b> Some History</a></li>
<li class="chapter" data-level="6.2" data-path="chap6.html"><a href="chap6.html#experiments"><i class="fa fa-check"></i><b>6.2</b> Experiments</a></li>
<li class="chapter" data-level="6.3" data-path="chap6.html"><a href="chap6.html#more-terminology"><i class="fa fa-check"></i><b>6.3</b> More terminology</a></li>
<li class="chapter" data-level="6.4" data-path="chap6.html"><a href="chap6.html#randomness"><i class="fa fa-check"></i><b>6.4</b> Randomness</a></li>
<li class="chapter" data-level="6.5" data-path="chap6.html"><a href="chap6.html#positive-and-negative-controls"><i class="fa fa-check"></i><b>6.5</b> Positive and Negative Controls</a></li>
<li class="chapter" data-level="6.6" data-path="chap6.html"><a href="chap6.html#blinding-of-experiments"><i class="fa fa-check"></i><b>6.6</b> Blinding of experiments</a></li>
<li class="chapter" data-level="6.7" data-path="chap6.html"><a href="chap6.html#covariates"><i class="fa fa-check"></i><b>6.7</b> Covariates</a></li>
<li class="chapter" data-level="6.8" data-path="chap6.html"><a href="chap6.html#natural-experiments-or-natural-experiments"><i class="fa fa-check"></i><b>6.8</b> “Natural” Experiments or Natural “Experiments”</a></li>
<li class="chapter" data-level="6.9" data-path="chap6.html"><a href="chap6.html#random-effects-and-blocking"><i class="fa fa-check"></i><b>6.9</b> Random effects and Blocking</a></li>
<li class="chapter" data-level="6.10" data-path="chap6.html"><a href="chap6.html#power"><i class="fa fa-check"></i><b>6.10</b> Power</a></li>
<li class="chapter" data-level="6.11" data-path="chap6.html"><a href="chap6.html#factors-affecting-the-power-of-a-test"><i class="fa fa-check"></i><b>6.11</b> Factors affecting the Power of a Test</a></li>
<li class="chapter" data-level="6.12" data-path="chap6.html"><a href="chap6.html#built-in-r-functions-for-power-analysis"><i class="fa fa-check"></i><b>6.12</b> Built-in R Functions for Power Analysis</a></li>
<li class="chapter" data-level="6.13" data-path="chap6.html"><a href="chap6.html#power-of-the-t-test"><i class="fa fa-check"></i><b>6.13</b> Power of the t-test</a></li>
<li class="chapter" data-level="6.14" data-path="chap6.html"><a href="chap6.html#exercises"><i class="fa fa-check"></i><b>6.14</b> Exercises</a></li>
<li class="chapter" data-level="6.15" data-path="chap6.html"><a href="chap6.html#package-pwr"><i class="fa fa-check"></i><b>6.15</b> Package <tt>pwr</tt></a></li>
<li class="chapter" data-level="6.16" data-path="chap6.html"><a href="chap6.html#exercises-1"><i class="fa fa-check"></i><b>6.16</b> Exercises</a></li>
<li class="chapter" data-level="6.17" data-path="chap6.html"><a href="chap6.html#effect-sizes"><i class="fa fa-check"></i><b>6.17</b> Effect Sizes</a></li>
<li class="chapter" data-level="6.18" data-path="chap6.html"><a href="chap6.html#exercises-2"><i class="fa fa-check"></i><b>6.18</b> Exercises</a></li>
<li class="chapter" data-level="6.19" data-path="chap6.html"><a href="chap6.html#power-curves"><i class="fa fa-check"></i><b>6.19</b> Power Curves</a></li>
<li class="chapter" data-level="6.20" data-path="chap6.html"><a href="chap6.html#power-analysis-by-simulation"><i class="fa fa-check"></i><b>6.20</b> Power Analysis by Simulation</a></li>
<li class="chapter" data-level="6.21" data-path="chap6.html"><a href="chap6.html#exercise"><i class="fa fa-check"></i><b>6.21</b> Exercise</a></li>
<li class="chapter" data-level="6.22" data-path="chap6.html"><a href="chap6.html#references"><i class="fa fa-check"></i><b>6.22</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap7.html"><a href="chap7.html"><i class="fa fa-check"></i><b>7</b> LinearModels</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chap7.html"><a href="chap7.html#graphing-the-iris-data"><i class="fa fa-check"></i><b>7.1</b> Graphing the Iris data</a></li>
<li class="chapter" data-level="7.2" data-path="chap7.html"><a href="chap7.html#good-resources-for-graphing"><i class="fa fa-check"></i><b>7.2</b> Good Resources for Graphing</a></li>
<li class="chapter" data-level="7.3" data-path="chap7.html"><a href="chap7.html#analysing-the-iris-data"><i class="fa fa-check"></i><b>7.3</b> Analysing the iris data</a></li>
<li class="chapter" data-level="7.4" data-path="chap7.html"><a href="chap7.html#model-diagnostics"><i class="fa fa-check"></i><b>7.4</b> Model Diagnostics</a></li>
<li class="chapter" data-level="7.5" data-path="chap7.html"><a href="chap7.html#analysis-using-t-test"><i class="fa fa-check"></i><b>7.5</b> Analysis using t test</a></li>
<li class="chapter" data-level="7.6" data-path="chap7.html"><a href="chap7.html#analysis-using-anova"><i class="fa fa-check"></i><b>7.6</b> Analysis using ANOVA</a></li>
<li class="chapter" data-level="7.7" data-path="chap7.html"><a href="chap7.html#analysis-using-regression"><i class="fa fa-check"></i><b>7.7</b> Analysis using Regression</a></li>
<li class="chapter" data-level="7.8" data-path="chap7.html"><a href="chap7.html#points-to-note"><i class="fa fa-check"></i><b>7.8</b> Points to Note</a></li>
<li class="chapter" data-level="7.9" data-path="chap7.html"><a href="chap7.html#summary"><i class="fa fa-check"></i><b>7.9</b> Summary</a></li>
<li class="chapter" data-level="7.10" data-path="chap7.html"><a href="chap7.html#linear-models"><i class="fa fa-check"></i><b>7.10</b> Linear Models</a></li>
<li class="chapter" data-level="7.11" data-path="chap7.html"><a href="chap7.html#matrix-notation-for-linear-models"><i class="fa fa-check"></i><b>7.11</b> Matrix Notation for Linear Models</a></li>
<li class="chapter" data-level="7.12" data-path="chap7.html"><a href="chap7.html#matrix-representation"><i class="fa fa-check"></i><b>7.12</b> Matrix Representation</a></li>
<li class="chapter" data-level="7.13" data-path="chap7.html"><a href="chap7.html#distributional-assumptions"><i class="fa fa-check"></i><b>7.13</b> Distributional Assumptions</a></li>
<li class="chapter" data-level="7.14" data-path="chap7.html"><a href="chap7.html#estimation-ordinary-least-squares"><i class="fa fa-check"></i><b>7.14</b> Estimation: Ordinary Least Squares</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap8.html"><a href="chap8.html"><i class="fa fa-check"></i><b>8</b> Generalised Least Squares</a>
<ul>
<li class="chapter" data-level="8.1" data-path="chap8.html"><a href="chap8.html#estimation-gls"><i class="fa fa-check"></i><b>8.1</b> Estimation: GLS</a></li>
<li class="chapter" data-level="8.2" data-path="chap8.html"><a href="chap8.html#gls-example-phylogenetic-autocorrelation"><i class="fa fa-check"></i><b>8.2</b> GLS example: Phylogenetic autocorrelation</a></li>
<li class="chapter" data-level="8.3" data-path="chap8.html"><a href="chap8.html#gls-example-phylogenetic-autocorrelation-1"><i class="fa fa-check"></i><b>8.3</b> GLS example: Phylogenetic autocorrelation</a></li>
<li class="chapter" data-level="8.4" data-path="chap8.html"><a href="chap8.html#gls-example-time-series"><i class="fa fa-check"></i><b>8.4</b> GLS example: Time Series</a></li>
<li class="chapter" data-level="8.5" data-path="chap8.html"><a href="chap8.html#lynx-data"><i class="fa fa-check"></i><b>8.5</b> Lynx Data</a></li>
<li class="chapter" data-level="8.6" data-path="chap8.html"><a href="chap8.html#acf-and-pacf"><i class="fa fa-check"></i><b>8.6</b> ACF and PACF</a></li>
<li class="chapter" data-level="8.7" data-path="chap8.html"><a href="chap8.html#autoregression-of-lynx-data"><i class="fa fa-check"></i><b>8.7</b> Autoregression of Lynx Data</a></li>
<li class="chapter" data-level="8.8" data-path="chap8.html"><a href="chap8.html#gls-autoregression-model-of-lynx-data"><i class="fa fa-check"></i><b>8.8</b> GLS Autoregression model of Lynx data</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap9.html"><a href="chap9.html"><i class="fa fa-check"></i><b>9</b> Categorical Data Analysis</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chap9.html"><a href="chap9.html#types-of-data"><i class="fa fa-check"></i><b>9.1</b> Types of Data</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html"><i class="fa fa-check"></i><b>10</b> Multinomial Experiments</a>
<ul>
<li class="chapter" data-level="10.1" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#example-1.-specified-cell-probabilities"><i class="fa fa-check"></i><b>10.1</b> Example 1. Specified Cell Probabilities</a></li>
<li class="chapter" data-level="10.2" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#example-2-goodness-of-fit"><i class="fa fa-check"></i><b>10.2</b> Example 2: Goodness-of-fit</a></li>
<li class="chapter" data-level="10.3" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#example-3-contingency-tables"><i class="fa fa-check"></i><b>10.3</b> Example 3: Contingency Tables</a></li>
<li class="chapter" data-level="10.4" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#assumptions-of-the-x2-test"><i class="fa fa-check"></i><b>10.4</b> Assumptions of the <span class="math inline">\(X^2\)</span> Test</a></li>
<li class="chapter" data-level="10.5" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#loglinear-models"><i class="fa fa-check"></i><b>10.5</b> Loglinear Models</a></li>
<li class="chapter" data-level="10.6" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#generalised-linear-models"><i class="fa fa-check"></i><b>10.6</b> Generalised Linear Models</a></li>
<li class="chapter" data-level="10.7" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#the-general-linear-model-for-normal-responses"><i class="fa fa-check"></i><b>10.7</b> The General Linear Model for Normal Responses</a></li>
<li class="chapter" data-level="10.8" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#the-poisson-glm"><i class="fa fa-check"></i><b>10.8</b> The Poisson GLM</a></li>
<li class="chapter" data-level="10.9" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#fitting-the-poisson-glm"><i class="fa fa-check"></i><b>10.9</b> Fitting the Poisson GLM</a></li>
<li class="chapter" data-level="10.10" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#mode-diagnostics"><i class="fa fa-check"></i><b>10.10</b> Mode Diagnostics</a></li>
<li class="chapter" data-level="10.11" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#the-binomial-glm"><i class="fa fa-check"></i><b>10.11</b> The Binomial GLM</a></li>
<li class="chapter" data-level="10.12" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#example-beetle-mortality-to-insecticide"><i class="fa fa-check"></i><b>10.12</b> Example: Beetle mortality to insecticide</a></li>
<li class="chapter" data-level="10.13" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#diagnostics"><i class="fa fa-check"></i><b>10.13</b> Diagnostics</a></li>
<li class="chapter" data-level="10.14" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#another-approach-to-diagnostics"><i class="fa fa-check"></i><b>10.14</b> Another approach to Diagnostics</a></li>
<li class="chapter" data-level="10.15" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#some-theory"><i class="fa fa-check"></i><b>10.15</b> Some theory</a></li>
<li class="chapter" data-level="10.16" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#simple-example-the-poisson-distribution"><i class="fa fa-check"></i><b>10.16</b> Simple example: The Poisson distribution</a></li>
<li class="chapter" data-level="10.17" data-path="multinomial-experiments.html"><a href="multinomial-experiments.html#issues-when-fitting-with-glms"><i class="fa fa-check"></i><b>10.17</b> Issues when fitting with GLMs</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIOL3360</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multinomial-experiments" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> Multinomial Experiments<a href="multinomial-experiments.html#multinomial-experiments" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The simplest type of experiment that leads to categorical data is the <code>multinomial</code> experiment. A multinomial experiment consists of <span class="math inline">\(n\)</span> identical trials. The outcome of each trial falls into one of k categories or cells. The probability that the outcome of a single trial will fall in a particular cell, say, cell i is <span class="math inline">\(p_i\)</span> , where <span class="math inline">\(i = 1, 2, \dots , k\)</span>, and remains the same from trial to trial. Note that:</p>
<p><span class="math display">\[p_1 + p_2 + p_3 + \dots + p_k = 1\]</span>
(This is an example of the Law of Total Probability (LOTP). In the end, all the probabilities in a problem have to sum to one. Remembering this rule can help you solve many statistical problems.)</p>
<p>In a multinomial experiment, the trials are independent. We are interested in the <span class="math inline">\(n_1, n_2, n_3, \dots, n_k\)</span> where <span class="math inline">\(n_i\)</span> for <span class="math inline">\(i=1,2, \dots, k\)</span> is equal to the number of trials which the outcome falls into cell <span class="math inline">\(i\)</span>. Note that <span class="math inline">\(n_1+n_2+n_3+ \dots +n_k=n\)</span> The experiment can be modelled using a <strong>multinomial</strong> distribution with probability mass function: $</p>
<p><span class="math display">\[p(n_1, n_2, \dots, n_k)=\frac{n!}{n_1!n_2 \dots n_k!}p_1^{n_1}p_2^{n_2} \dots p_k^{n_k}
\]</span>
## Pearson’s <span class="math inline">\(X^2\)</span> test</p>
<p>[Karl Pearson (1857-1936)]{Karl_Pearson.jpg}</p>
<p>The <span class="math inline">\(X^2\)</span> test was proposed in 1900, and can be used for testing hypotheses about <span class="math inline">\(p_1, p_2, p_3, \dots, p_k\)</span> Suppose that <span class="math inline">\(n=100\)</span> balls were thrown into <span class="math inline">\(k\)</span> boxes. Further suppose that <span class="math inline">\(p_1=0.1\)</span>. What would the expected number of balls in box 1 be? This would just be <span class="math inline">\(E(n_1)=np_1=(100)(0.1)=10\)</span> Similarly for the other boxes, we have: <span class="math inline">\(E(n_i)=np_i, i= 1, 2, \dots, k\)</span></p>
<p>Suppose we postulate values for the <span class="math inline">\(p_i\)</span>s. If our hypothesis is correct, the <span class="math inline">\(n_i\)</span>s should not depart much from the expected values (remember residuals in regression? This is the same principle.) Hence it seems reasonable to use the deviations from the expected values in a test statistic: <span class="math inline">\(n_i-np_i, i=1 ,2, \dots, k\)</span></p>
<p>The test can then be constructed as:</p>
<p><span class="math display">\[\displaystyle X^2=\sum_{i=1}^k\frac{(n_i-np_i)^2}{np_i}=\sum_{i=1}^k\frac{[n_i-E(n_i)]^2}{E(n_i)}\]</span>
Asymptotically (for large <span class="math inline">\(n\)</span>), <span class="math inline">\(X^2\)</span> follows a <span class="math inline">\(\chi^2_{\nu}\)</span> distribution with <span class="math inline">\(\nu\)</span> degrees of freedom. The <span class="math inline">\(\chi^2\)</span> distibution as Probability density function</p>
<p><span class="math display">\[f(y)=\frac{(y)^{\nu/2-1}e^{-y/2}}{2^{\nu/2}\Gamma(\nu/2)}, y &gt; 0\]</span>
It’s easier to visualise the <span class="math inline">\(\chi^2\)</span> distribution:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="multinomial-experiments.html#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb111-2"><a href="multinomial-experiments.html#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">80</span>)), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb111-3"><a href="multinomial-experiments.html#cb111-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span> (x) <span class="fu">dchisq</span>(x, <span class="at">df =</span> <span class="dv">1</span>), <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="fu">aes</span>(<span class="at">colour =</span> <span class="st">&quot;1&quot;</span>)) <span class="sc">+</span></span>
<span id="cb111-4"><a href="multinomial-experiments.html#cb111-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span> (x) <span class="fu">dchisq</span>(x, <span class="at">df =</span> <span class="dv">5</span>), <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="fu">aes</span>(<span class="at">colour =</span> <span class="st">&quot;5&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb111-5"><a href="multinomial-experiments.html#cb111-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span> (x) <span class="fu">dchisq</span>(x, <span class="at">df =</span> <span class="dv">50</span>), <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="fu">aes</span>(<span class="at">colour =</span> <span class="st">&quot;50&quot;</span>)) <span class="sc">+</span></span>
<span id="cb111-6"><a href="multinomial-experiments.html#cb111-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Density&quot;</span>) <span class="sc">+</span> </span>
<span id="cb111-7"><a href="multinomial-experiments.html#cb111-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_colour_manual</span>(<span class="st">&quot;Degrees of Freedom&quot;</span>, <span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), </span>
<span id="cb111-8"><a href="multinomial-experiments.html#cb111-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">breaks=</span><span class="fu">c</span>(<span class="st">&quot;1&quot;</span>, <span class="st">&quot;5&quot;</span>, <span class="st">&quot;50&quot;</span>))</span></code></pre></div>
<p><img src="BIOL3360_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<div id="example-1.-specified-cell-probabilities" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Example 1. Specified Cell Probabilities<a href="multinomial-experiments.html#example-1.-specified-cell-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Frequently we know what the cell probabilities (the <span class="math inline">\(p_i\)</span>’s) should be, based on a scientific theory. For example, Mendelian genetic theory predicts that peas falling into the following classes are distributed 9:3:3:1 with the following phenotypes: Round/Yellow, Wrinkled/Yellow, Round/Green, Wrinkled/Green. Say, N = 100 peas are examined, with the following counts:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="multinomial-experiments.html#cb112-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">56</span>, <span class="dv">19</span>, <span class="dv">17</span>, <span class="dv">8</span>)</span>
<span id="cb112-2"><a href="multinomial-experiments.html#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;RY&quot;</span>, <span class="st">&quot;WY&quot;</span>, <span class="st">&quot;RG&quot;</span>, <span class="st">&quot;WG&quot;</span>)</span>
<span id="cb112-3"><a href="multinomial-experiments.html#cb112-3" aria-hidden="true" tabindex="-1"></a>counts</span></code></pre></div>
<pre><code>## RY WY RG WG 
## 56 19 17  8</code></pre>
<p>\end{itemize}
\end{itemize}
\end{frame}</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="multinomial-experiments.html#cb114-1" aria-hidden="true" tabindex="-1"></a>ratio <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb114-2"><a href="multinomial-experiments.html#cb114-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> ratio <span class="sc">/</span> <span class="fu">sum</span>(ratio)</span>
<span id="cb114-3"><a href="multinomial-experiments.html#cb114-3" aria-hidden="true" tabindex="-1"></a>expected <span class="ot">&lt;-</span> <span class="fu">sum</span>(counts) <span class="sc">*</span> p</span>
<span id="cb114-4"><a href="multinomial-experiments.html#cb114-4" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((counts <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> expected)</span>
<span id="cb114-5"><a href="multinomial-experiments.html#cb114-5" aria-hidden="true" tabindex="-1"></a>x2</span></code></pre></div>
<pre><code>## [1] 0.6577778</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="multinomial-experiments.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(x2, <span class="at">df=</span><span class="dv">3</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.8830872</code></pre>
<p>Because the expected proportions come from theory, and not the data themselves, we do not lose any degrees of freedom apart from the restriction that <span class="math inline">\(n_1+n_2+n_3+n_4=100\)</span>. Therefore there are <span class="math inline">\(k-1=4-1=3\)</span> degrees of freedom. Hence, because the p-value is &gt;&gt; 0.05, we do not reject the null hypothesis that the peas follow the Mendelian model. Of course, we can easily do this using the built-in <code>chisq.test()</code> function in R:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="multinomial-experiments.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(counts, <span class="at">p =</span> ratio, <span class="at">rescale.p =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  counts
## X-squared = 0.65778, df = 3, p-value = 0.8831</code></pre>
</div>
<div id="example-2-goodness-of-fit" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Example 2: Goodness-of-fit<a href="multinomial-experiments.html#example-2-goodness-of-fit" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <span class="math inline">\(X^2\)</span> test is also useful for testing whether data are consistent with a particular probability distribution. The idea is to use <span class="math inline">\(X^2\)</span> to measure the <em>fit</em> of the probability model to the data. Significant lack of fit implies rejection of the null hypothesis of <em>no departure from the model</em>. For example, the Poisson distribution is often used to model “count” data. Consider the following data:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="multinomial-experiments.html#cb120-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">birds=</span><span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">frequency=</span><span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">19</span>, <span class="dv">9</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">0</span>))</span>
<span id="cb120-2"><a href="multinomial-experiments.html#cb120-2" aria-hidden="true" tabindex="-1"></a>dat</span></code></pre></div>
<pre><code>##   birds frequency
## 1     0        16
## 2     1        19
## 3     2         9
## 4     3         4
## 5     4         2
## 6     5         0</code></pre>
<p>Note that birds = 5 really means 5 <strong>or greater</strong>. The expected number of birds per site is just:</p>
<p><span class="math display">\[
\hat{\lambda}=\frac{(0)(16) + (1)(19) + (2)(9) + (3)(4) + (4)(2)}{16 + 19 + 9 + 4 +2 }=1.14
\]</span>
Aside: Note that the numerator consists of additions and multiplications. This strongly suggests that we could summarise the numerator by using vector multiplication:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="multinomial-experiments.html#cb122-1" aria-hidden="true" tabindex="-1"></a>lambdahat <span class="ot">&lt;-</span> <span class="fu">with</span>(dat, (birds <span class="sc">%*%</span> frequency) <span class="sc">/</span> <span class="fu">sum</span>(frequency))</span>
<span id="cb122-2"><a href="multinomial-experiments.html#cb122-2" aria-hidden="true" tabindex="-1"></a>lambdahat</span></code></pre></div>
<pre><code>##      [,1]
## [1,] 1.14</code></pre>
<p>The cell probabilities are just:
<span class="math display">\[\begin{align*}
    p(y \mid  \lambda) &amp;= \frac{\lambda^y e^{-\lambda}}{y!}, y= 0, 1, 2, \dots \\
    p_0 &amp;= e^{-\lambda} = 0.3198 \\
    p_1 &amp;= \lambda e^{-\lambda} = 0.3646 \\
    p_2 &amp;= \frac{\lambda^2e^{-\lambda}}{2} = 0.2078 \\
    p_3 &amp;= \frac{\lambda^3e^{-\lambda}}{6} = 0.0790 \\
    p_{4+} &amp;= 1 - p_0 - p_1 - p_2 - p_3 = 0.0288 \; \text{(LOTP)}
  \end{align*}
  \]</span>
The expected values for each cell are just:
<span class="math display">\[
  \begin{align*}
    E(n_0) &amp;=(50)(0.3198)=15.9910\\
    E(n_1) &amp;=(50)(0.3646)=18.2297\\
    E(n_2) &amp;=(50)(0.2078)=10.3909\\
    E(n_3) &amp;=(50)(0.0790)=3.9486\\
    E(n_{4+}) &amp;= (50)(0.0288)=1.4399
  \end{align*}
  \]</span>
Note that <span class="math inline">\(E(n_3)\)</span> and <span class="math inline">\(E(n_{4+})\)</span> are both <span class="math inline">\(&lt; 5\)</span>. The <span class="math inline">\(X^2\)</span> approximation to the <span class="math inline">\(\chi^2\)</span> distribution is unreliable for such low values. Hence, we should pool these last 2 categories: <span class="math inline">\(E(n_{3+})=3.9486+1.4399=5.3884\)</span> And we now have <span class="math inline">\(k=4\)</span> categories. We now have to Calculate <span class="math inline">\(X^2\)</span>:
<span class="math display">\[
  \begin{align*} X^2&amp;=\sum_{i=1}^k\frac{(n_i-np_i)^2}{np_i}\\
    &amp;=\sum_{i=1}^k\frac{[n_i-E(n_i)]^2}{E(n_i)}\\
    &amp;= 0.2882\\
   df &amp;= k-1-1=4-2=2 \\
   p&amp;=\chi^2_2(0.4373)=0.8658 \gg 0.05
   \end{align*}
   \]</span>
Therefore we do <strong>not</strong> reject the null hypothesis that the data come from a Poisson distribution. Here is the above analysis in R:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="multinomial-experiments.html#cb124-1" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>, lambdahat), <span class="dv">1</span><span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>, lambdahat)))</span>
<span id="cb124-2"><a href="multinomial-experiments.html#cb124-2" aria-hidden="true" tabindex="-1"></a>probs</span></code></pre></div>
<pre><code>## [1] 0.3198190 0.3645937 0.2078184 0.1077689</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="multinomial-experiments.html#cb126-1" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> <span class="fu">c</span>(dat<span class="sc">$</span>frequency[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="fu">sum</span>(dat<span class="sc">$</span>frequency[<span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>]))</span>
<span id="cb126-2"><a href="multinomial-experiments.html#cb126-2" aria-hidden="true" tabindex="-1"></a>pooled</span></code></pre></div>
<pre><code>## [1] 16 19  9  6</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="multinomial-experiments.html#cb128-1" aria-hidden="true" tabindex="-1"></a>expecteds <span class="ot">&lt;-</span> <span class="fu">sum</span>(pooled) <span class="sc">*</span> probs</span>
<span id="cb128-2"><a href="multinomial-experiments.html#cb128-2" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((pooled<span class="sc">-</span>expecteds)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>expecteds)</span>
<span id="cb128-3"><a href="multinomial-experiments.html#cb128-3" aria-hidden="true" tabindex="-1"></a>X2</span></code></pre></div>
<pre><code>## [1] 0.2881509</code></pre>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="multinomial-experiments.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(X2, <span class="at">df=</span><span class="dv">2</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.8658224</code></pre>
</div>
<div id="example-3-contingency-tables" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Example 3: Contingency Tables<a href="multinomial-experiments.html#example-3-contingency-tables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can use the <span class="math inline">\(X^2\)</span> test to analyse cross-classified tabular data. The most common use of <span class="math inline">\(X^2\)</span> is a test of <strong>independence</strong> of rows from columns. ie a test of <strong>association</strong> between rows and columns}. Here’s and example:</p>
<table>
<caption>Data on Students Publishing (continued below)</caption>
<colgroup>
<col width="60%" />
<col width="39%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">High input from Supervisor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>Supervisor 1st, Student mandatory 2nd</strong></td>
<td align="center">19</td>
</tr>
<tr class="even">
<td align="center"><strong>Student 1st, Supervisor mandatory 2nd</strong></td>
<td align="center">19</td>
</tr>
<tr class="odd">
<td align="center"><strong>Student 1st, Supervisor courtesy 2nd</strong></td>
<td align="center">3</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Medium Input</th>
<th align="center">Low Input</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>Supervisor 1st, Student mandatory 2nd</strong></td>
<td align="center">6</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center"><strong>Student 1st, Supervisor mandatory 2nd</strong></td>
<td align="center">41</td>
<td align="center">27</td>
</tr>
<tr class="odd">
<td align="center"><strong>Student 1st, Supervisor courtesy 2nd</strong></td>
<td align="center">7</td>
<td align="center">31</td>
</tr>
</tbody>
</table>
<p>The data are numbers of published papers by students, cross-classified by the order of authorship and the input from the supervisor. Usually, the author order in biology is to have the student first, except when there is a high level of input from the supervisor. ie when the student is a low contributor to the study.</p>
<p>We need to <strong>estimate</strong> the expected values (under the null hypothesis) in each cell. This is done by multiplying the appropriate row and column totals and dividing by the grand total: <span class="math inline">\(\widehat{E(n_{ij})}=\frac{r_ic_j}{n}\)</span>. We can then use the usual formula for <span class="math inline">\(X^2\)</span>, with degrees of freedom <span class="math inline">\((nrow - 1)(ncol - 1)\)</span>. Here’s how to do it in R:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="multinomial-experiments.html#cb132-1" aria-hidden="true" tabindex="-1"></a>mat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">19</span>, <span class="dv">41</span>, <span class="dv">27</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">31</span>), <span class="at">nrow=</span><span class="dv">3</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb132-2"><a href="multinomial-experiments.html#cb132-2" aria-hidden="true" tabindex="-1"></a>csum <span class="ot">&lt;-</span> <span class="fu">colSums</span>(mat)</span>
<span id="cb132-3"><a href="multinomial-experiments.html#cb132-3" aria-hidden="true" tabindex="-1"></a>rsum <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(mat)</span>
<span id="cb132-4"><a href="multinomial-experiments.html#cb132-4" aria-hidden="true" tabindex="-1"></a>expecteds <span class="ot">&lt;-</span> <span class="fu">outer</span>(rsum, csum) <span class="sc">/</span> <span class="fu">sum</span>(rsum)</span>
<span id="cb132-5"><a href="multinomial-experiments.html#cb132-5" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((mat <span class="sc">-</span> expecteds)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> expecteds)</span>
<span id="cb132-6"><a href="multinomial-experiments.html#cb132-6" aria-hidden="true" tabindex="-1"></a>X2</span></code></pre></div>
<pre><code>## [1] 57.36176</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="multinomial-experiments.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(X2, <span class="at">df =</span> <span class="dv">4</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1.038795e-11</code></pre>
<p>Therefore, we reject the null hypothesis. There <strong>is</strong> an association between authorship order and the amount of input by the supervisor. Of course, it is easy to use the <code>chisq.test()</code> function in R:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="multinomial-experiments.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(mat)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  mat
## X-squared = 57.362, df = 4, p-value = 1.039e-11</code></pre>
</div>
<div id="assumptions-of-the-x2-test" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Assumptions of the <span class="math inline">\(X^2\)</span> Test<a href="multinomial-experiments.html#assumptions-of-the-x2-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>The data must satisfy the assumptions of a multinomial experiment (independent trials, constant cell probabilities etc.)</li>
<li>Expected cell values should <strong>not</strong> be <span class="math inline">\(&lt; 5\)</span>. In this case the asymptotic approximation to the <span class="math inline">\(\chi^2\)</span> doesn’t hold. You can use other methods or use simulation (See <code>?chisq.test</code>)</li>
<li>The <strong>degrees of freedom for a contingency table</strong> = (r-1)(c-1)</li>
</ol>
</div>
<div id="loglinear-models" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Loglinear Models<a href="multinomial-experiments.html#loglinear-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Another approach, which works well for multiway tables, that is, tables with greater than 2 dimensions is the technique of log-linear modelling. Here is the 2-way table described above, analysed using a loglinear model. Notice that the loglm function has a formula argument that looks very similar to the formula argument for <code>aov()</code> and <code>lm()</code>. Note also that the output includes the value of the Pearson <span class="math inline">\(X^2\)</span> statistic.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="multinomial-experiments.html#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb138-2"><a href="multinomial-experiments.html#cb138-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">as.data.frame.table</span>(mat)</span>
<span id="cb138-3"><a href="multinomial-experiments.html#cb138-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Authorship&quot;</span>, <span class="st">&quot;Input&quot;</span>, <span class="st">&quot;Frequency&quot;</span>)</span>
<span id="cb138-4"><a href="multinomial-experiments.html#cb138-4" aria-hidden="true" tabindex="-1"></a>dat</span></code></pre></div>
<pre><code>##   Authorship Input Frequency
## 1          A     A        19
## 2          B     A        19
## 3          C     A         3
## 4          A     B         6
## 5          B     B        41
## 6          C     B         7
## 7          A     C         2
## 8          B     C        27
## 9          C     C        31</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="multinomial-experiments.html#cb140-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">loglm</span>(Frequency <span class="sc">~</span> Authorship <span class="sc">+</span> Input, <span class="at">data =</span> dat)</span>
<span id="cb140-2"><a href="multinomial-experiments.html#cb140-2" aria-hidden="true" tabindex="-1"></a>fit</span></code></pre></div>
<pre><code>## Call:
## loglm(formula = Frequency ~ Authorship + Input, data = dat)
## 
## Statistics:
##                       X^2 df     P(&gt; X^2)
## Likelihood Ratio 54.54193  4 4.052392e-11
## Pearson          57.36176  4 1.038791e-11</code></pre>
</div>
<div id="generalised-linear-models" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> Generalised Linear Models<a href="multinomial-experiments.html#generalised-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The most flexible approach to modelling non-Normal data is the framework of <strong>Generalised Linear Models</strong>. GLMs allow the fitting of linear models using a large variety of distributions, including the Normal distribution. For our purposes, we will use GLMs to analyse categorical data and binary data. First we need to discuss some theory, so we can relate the GLM framework to the ordinary linear model framework. This will allow us to see that GLMs are really just an extension of the linear models that we understand already. First, we set up the mathematical formulation.</p>
</div>
<div id="the-general-linear-model-for-normal-responses" class="section level2 hasAnchor" number="10.7">
<h2><span class="header-section-number">10.7</span> The General Linear Model for Normal Responses<a href="multinomial-experiments.html#the-general-linear-model-for-normal-responses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall that the ordinary linear model can be described in the following way:
<span class="math display">\[
\mathbf{Y}=\mathbf{X}\beta + \epsilon, \epsilon \sim N(0, \sigma^2\mathbf{I})
\]</span>
This can also be written as:
<span class="math display">\[
E(\mathbf{Y}) = \mathbf{\mu} = \mathbf{X}\beta, \mathbf{Y} \sim N(\mathbf{\mu}, \sigma^2\mathbf{I})
\]</span>
Or more generally:
<span class="math display">\[
g(\mathbf{\mu}) = \mathbf{X\beta},\; \mathbf{\mu} \sim f(\mathbf{\mu, \theta})
\]</span>
<span class="math inline">\(g(.)\)</span> is called the <strong>link function</strong>. For normally-distributed data, the link function is the <em>identity</em> function. ie <span class="math inline">\(f(x) = x\)</span>. <span class="math inline">\(\mathbf{X\beta}\)</span> is the <strong>linear predictor</strong>, the same as for the ordinary linear model. <span class="math inline">\(f(.)\)</span> is a probability distribution from the <strong>exponential family</strong> of distributions (more on those later!). <span class="math inline">\(\mu\)</span> is the <strong>Expectation</strong> of <span class="math inline">\(\mathbf{Y}\)</span> ie the mean values. <span class="math inline">\(E(\mathbf{Y})=\mu\)</span></p>
<p>Generalised Linear Models extend the General Linear Model in 2 directions:</p>
<ol style="list-style-type: decimal">
<li>The response variable can have a distribution other than the Normal distribution</li>
<li>The relationship between the response and explanatory variables need not be linear (on the scale of the response). That is, the link function allows us to use nonlinear functions of the linear predictor, which can be very useful.</li>
</ol>
</div>
<div id="the-poisson-glm" class="section level2 hasAnchor" number="10.8">
<h2><span class="header-section-number">10.8</span> The Poisson GLM<a href="multinomial-experiments.html#the-poisson-glm" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One example is the Poisson Generalized Linear Model, which has many uses including the modelling of count data:</p>
<p><span class="math display">\[log(E(\mathbf{Y}))=\mathbf{X\beta}, \; \mathbf{Y} \sim Poisson(\lambda)\]</span>
Note that the loglinear model is a special case of the Poisson GLM. The advantage of using the Poisson GLM instead of a loglinear model is that the Poisson GLM can incoporate continuous covariate, whereas the loglinear modelling formulation only works for categorical variables.</p>
</div>
<div id="fitting-the-poisson-glm" class="section level2 hasAnchor" number="10.9">
<h2><span class="header-section-number">10.9</span> Fitting the Poisson GLM<a href="multinomial-experiments.html#fitting-the-poisson-glm" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We shall fit the Poisson GLM to the previous contingency table data.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="multinomial-experiments.html#cb142-1" aria-hidden="true" tabindex="-1"></a>fit.full <span class="ot">&lt;-</span> <span class="fu">glm</span>(Frequency <span class="sc">~</span> Authorship <span class="sc">*</span> Input, <span class="at">data =</span> dat, <span class="at">family =</span> poisson)</span>
<span id="cb142-2"><a href="multinomial-experiments.html#cb142-2" aria-hidden="true" tabindex="-1"></a>fit.noint <span class="ot">&lt;-</span> <span class="fu">glm</span>(Frequency <span class="sc">~</span> Authorship <span class="sc">+</span> Input, <span class="at">data =</span> dat, <span class="at">family =</span> poisson)</span>
<span id="cb142-3"><a href="multinomial-experiments.html#cb142-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit.noint, fit.full, <span class="at">test =</span> <span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: Frequency ~ Authorship + Input
## Model 2: Frequency ~ Authorship * Input
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1         4     54.542                          
## 2         0      0.000  4   54.542 4.052e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="multinomial-experiments.html#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare with the loglinear model output:</span></span>
<span id="cb144-2"><a href="multinomial-experiments.html#cb144-2" aria-hidden="true" tabindex="-1"></a>fit</span></code></pre></div>
<pre><code>## Call:
## loglm(formula = Frequency ~ Authorship + Input, data = dat)
## 
## Statistics:
##                       X^2 df     P(&gt; X^2)
## Likelihood Ratio 54.54193  4 4.052392e-11
## Pearson          57.36176  4 1.038791e-11</code></pre>
<p>Notice that we have constructed a likelihood ratio <span class="math inline">\(X^2\)</span> test by comparing Poisson GLMs, one with an interaction term and one without. The statistic is equal to 54.542 with a p-value close to zero. Notice this is the same as the Likelihood Ratio statistic from the loglinear model! So there is a close mathematical relationship between Poisson GLMs, loglinear models, and the Pearson <span class="math inline">\(X^2\)</span> statistic. This commonality of the underlying mathematics makes it clear that choosing an analysis method for count data is really just a convenience. For many situations, you could use any of the 3 methods (contingency tables, loglinear models, Poisson GLM).</p>
</div>
<div id="mode-diagnostics" class="section level2 hasAnchor" number="10.10">
<h2><span class="header-section-number">10.10</span> Mode Diagnostics<a href="multinomial-experiments.html#mode-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Model diagnostics for Generalised Linear Models work in a similar way to ordinary linear models, except they are sometimes harder to interpret. Importantly, on the scale of the link function (which is usually the log function for a Poisson GLM), there should be no relationship between the residuals and the fitted values, corresponding to the assumption of homoskedasticity in the general linear model. Similarly, the residuals should be approximately Normal on the scale of the link function.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="multinomial-experiments.html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb146-2"><a href="multinomial-experiments.html#cb146-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit.noint)</span></code></pre></div>
<p><img src="BIOL3360_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
</div>
<div id="the-binomial-glm" class="section level2 hasAnchor" number="10.11">
<h2><span class="header-section-number">10.11</span> The Binomial GLM<a href="multinomial-experiments.html#the-binomial-glm" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Binomial GLM is useful for modelling data where the response variable has 2 categories, for example survival (lived/died), sex ratio (male/female), response to a drug (yes/no), birds in a forest fragment (present/absent) or exams (pass/fail). Poisson and Binomial GLMs are probably the most often used in the analysis of biological data. The Binomial GLM has the following form:</p>
<p><span class="math display">\[g(E(\mathbf{Y}))= \mathbf{X\beta}, \; \mathbf{Y} \sim Binomial(n, p)\]</span>
<span class="math inline">\(g(.)\)</span> is the link function. It can take several forms. It <em>links</em> the Expected value of the response (<span class="math inline">\(\mathbf{Y}\)</span>) to the linear predictor. The <strong>canonical</strong> link function for the binomial distribution is the logit function:
<span class="math display">\[logit(p)=\log\left(\frac{p}{(1-p)}\right)\]</span></p>
</div>
<div id="example-beetle-mortality-to-insecticide" class="section level2 hasAnchor" number="10.12">
<h2><span class="header-section-number">10.12</span> Example: Beetle mortality to insecticide<a href="multinomial-experiments.html#example-beetle-mortality-to-insecticide" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Groups of beetles were exposed to different concentrations of insecticide, and the number that survived or killed by the insecticide was recorded. A binomial GLM was used in R to model the relationship between survival and insecticide dose:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="multinomial-experiments.html#cb147-1" aria-hidden="true" tabindex="-1"></a>Experiment <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Dose =</span> <span class="fu">c</span>(<span class="fl">1.6907</span>, <span class="fl">1.7242</span>, <span class="fl">1.7552</span>, <span class="fl">1.7842</span>, <span class="fl">1.8113</span>,</span>
<span id="cb147-2"><a href="multinomial-experiments.html#cb147-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="fl">1.8369</span>, <span class="fl">1.8610</span>, <span class="fl">1.8839</span>),</span>
<span id="cb147-3"><a href="multinomial-experiments.html#cb147-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Number.Exposed =</span> <span class="fu">c</span>(<span class="dv">59</span>, <span class="dv">60</span>, <span class="dv">62</span>, <span class="dv">56</span>, <span class="dv">63</span>, <span class="dv">59</span>, <span class="dv">63</span>, <span class="dv">60</span>),</span>
<span id="cb147-4"><a href="multinomial-experiments.html#cb147-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Number.Killed =</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">13</span>, <span class="dv">18</span>, <span class="dv">28</span>, <span class="dv">52</span>, <span class="dv">53</span>, <span class="dv">61</span>, <span class="dv">60</span>))</span>
<span id="cb147-5"><a href="multinomial-experiments.html#cb147-5" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(Number.Exposed <span class="sc">-</span> Number.Killed, Number.Killed) <span class="sc">~</span> Dose,</span>
<span id="cb147-6"><a href="multinomial-experiments.html#cb147-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> Experiment, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span>logit))</span>
<span id="cb147-7"><a href="multinomial-experiments.html#cb147-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(Number.Exposed - Number.Killed, Number.Killed) ~ 
##     Dose, family = binomial(link = logit), data = Experiment)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6622  -1.0517  -0.6809   0.3001   1.5211  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   59.574      5.078   11.73   &lt;2e-16 ***
## Dose         -33.618      2.853  -11.78   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 278.5592  on 7  degrees of freedom
## Residual deviance:   9.8783  on 6  degrees of freedom
## AIC: 40.674
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>We can see that there is a strong negative relationship between survivorship (as a proportion) and insecticide dose, as measured by the Dose coefficient in the model summary. But before going further, we should look at some diagnostic plots to see if our model appears reasonable. We see that the sample size (the number of groups exposed to insecticide) is quite small, but there seems to be no strong departures from the usual assumptions of no relationship between the residuals and fitted values, and the normality of the residuals (on the scale of the link function, which in this case is the logit() function).</p>
</div>
<div id="diagnostics" class="section level2 hasAnchor" number="10.13">
<h2><span class="header-section-number">10.13</span> Diagnostics<a href="multinomial-experiments.html#diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="multinomial-experiments.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb149-2"><a href="multinomial-experiments.html#cb149-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit)</span></code></pre></div>
<p><img src="BIOL3360_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
</div>
<div id="another-approach-to-diagnostics" class="section level2 hasAnchor" number="10.14">
<h2><span class="header-section-number">10.14</span> Another approach to Diagnostics<a href="multinomial-experiments.html#another-approach-to-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The plot of the residuals versus the fitted values for GLMs can be hard to interpret, as the data are non-normal, or not even continuous. A package that can provide diagnostic plots that <strong>are</strong> interpretable in the same way as the general linear model is the <code>DHARMa</code> package. It works by simulating residuals from the model and plotting these standardised, simulated residuals using the usual plots. Here is an example:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="multinomial-experiments.html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb150-2"><a href="multinomial-experiments.html#cb150-2" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">simulateResiduals</span>(fit, <span class="at">plot=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="BIOL3360_files/figure-html/unnamed-chunk-72-1.png" width="672" />
Notice that the left-hand plot looks like the usual quantile-quantile plot, but with the results of some extra tests plotted on it. In fact, this is actually a quantile-quantile plot based on the <strong>Uniform</strong> distribution. The right-hand plot is like the residuals versus the fitted values. You can see that this plot has a <code>hump</code> in it, which was not obvious from the ordinary diagnostic plots. This suggests that the data may actually follow a parabolic curve, which is described by a quadratic polynomial. We can fit a model with both a linear term and a quadratic term, and see if it is better than the model with just the linear term.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="multinomial-experiments.html#cb151-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(Number.Exposed <span class="sc">-</span> Number.Killed, Number.Killed) <span class="sc">~</span> <span class="fu">poly</span>(Dose,<span class="dv">2</span>),</span>
<span id="cb151-2"><a href="multinomial-experiments.html#cb151-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> Experiment, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span>logit))</span>
<span id="cb151-3"><a href="multinomial-experiments.html#cb151-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(Number.Exposed - Number.Killed, Number.Killed) ~ 
##     poly(Dose, 2), family = binomial(link = logit), data = Experiment)
## 
## Deviance Residuals: 
##       1        2        3        4        5        6        7        8  
##  0.3262  -0.7598   0.3934   0.5521  -1.0252   0.5541   0.3984  -0.8577  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -1.0315     0.2044  -5.047 4.48e-07 ***
## poly(Dose, 2)1  -6.6299     0.6423 -10.323  &lt; 2e-16 ***
## poly(Dose, 2)2  -1.3391     0.5465  -2.450   0.0143 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 278.5592  on 7  degrees of freedom
## Residual deviance:   3.3958  on 5  degrees of freedom
## AIC: 36.192
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>We see that indeed there is a significant 2nd order polynomial term (<span class="math inline">\(p = 0.0143\)</span>). So it looks like the polynomial is a better fit compared to the plain linear model. However, there is still a strong linear component, although highly significant, the effect size is not as great (-6.6299).</p>
</div>
<div id="some-theory" class="section level2 hasAnchor" number="10.15">
<h2><span class="header-section-number">10.15</span> Some theory<a href="multinomial-experiments.html#some-theory" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The theory for GLMs was first worked out for exponential family distributions. These are distributions which can have their probability density (mass) functions written in the following form:</p>
<p><span class="math display">\[f(y\mid\theta)= e^{a(y)b(\theta)+c(\theta)+d(y)}\]</span>
where y is the data and <span class="math inline">\(\theta\)</span> is a vector of parameters. <span class="math inline">\(b(\theta)\)</span> is known as the <code>natural parameter</code> and defines the <strong>canonical</strong> link function. If <span class="math inline">\(a(y) = y\)</span>, then the function is said to be in <strong>canonical form</strong>.</p>
</div>
<div id="simple-example-the-poisson-distribution" class="section level2 hasAnchor" number="10.16">
<h2><span class="header-section-number">10.16</span> Simple example: The Poisson distribution<a href="multinomial-experiments.html#simple-example-the-poisson-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Poisson distribution has probability mass function:</p>
<p><span class="math display">\[f(y\mid \lambda) = \frac{\lambda^y e^{-\lambda}}{y!}, \; y = 0, 1, 2, \ldots\]</span>
It can be written in exponential form as:</p>
<p><span class="math display">\[f(y \mid \lambda) = \exp(y \log \lambda - \lambda - \log y!)\]</span>
Note that <span class="math inline">\(a(y) = y\)</span> so the distribution is in canonical form. Also, the natural parameter <span class="math inline">\(b(\lambda) = \log \lambda\)</span> so <span class="math inline">\(\log()\)</span> is the canonical link function.</p>
<p>##The Binomial distribution in exponential form
The Binomial distribution has probability mass function:</p>
<p><span class="math display">\[f(y \mid p) = \binom{n}{y} p^y(1-p)^{n-y}\]</span></p>
<p>In exponential form:
<span class="math display">\[
  \begin{align*}
  f(y \mid p) &amp;= \exp \left[  y \log p - y \log(1-p)+n \log(1-p) + log \binom{n}{y} \right] \\
    &amp;= \exp \left[ y \log \frac{p}{1-p}+ n \log(1-p) + log \binom{n}{y} \right]
  \end{align*}
  \]</span>
which is in canonical form and the natural parameter is <span class="math inline">\(\log \frac{p}{(1-p)}\)</span>.</p>
</div>
<div id="issues-when-fitting-with-glms" class="section level2 hasAnchor" number="10.17">
<h2><span class="header-section-number">10.17</span> Issues when fitting with GLMs<a href="multinomial-experiments.html#issues-when-fitting-with-glms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One problem that can occur is overdispersion. This is particularly common with Poisson models. Overdispersion occurs when the variance of the data is greater than the mean. Since in a Poisson model, the variance <em>equals</em> the mean, this is a strong restriction. There are several solutions, including fitting by a technique called quasilikelihood, which is beyond the scope of this course. An alternative approach which tends to work much better is to look for a discrete distribution that can model the overdispersion. In practice, the Negative Binomial distribution often works quite well. The Negative Binomial is a discrete distribution, taking values 0, 1, 2, … so it is suitable for count data.</p>
<p>Another problem that can occur, particularly in count data is <strong>zero inflation</strong>. When using a Poisson model, it is expected to get at least a few zeros in the data set. However, it is often found that there are way too many zeros than predicted by a Poisson distribution:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="multinomial-experiments.html#cb153-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Poisson=</span><span class="fu">c</span>(<span class="fu">rpois</span>(<span class="dv">50</span>, <span class="at">lambda=</span><span class="dv">5</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">50</span>)))</span>
<span id="cb153-2"><a href="multinomial-experiments.html#cb153-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(dat, <span class="fu">hist</span>(Poisson, <span class="at">main =</span> <span class="st">&quot;Zero Inflation&quot;</span>))</span></code></pre></div>
<p><img src="BIOL3360_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>In this case, a zero-inflated Poisson model (ZIP) might work better, or a <strong>hurdle</strong> model. Again, these are beyond the scope of the course.</p>
<p>Another issue is how to choose an appropriate link function. While the canonical link function usually performs pretty well, other link functions are possible. For a binomial model, R provides the logit, probit, cauchit, log, and complementary log-log. See <code>?family</code> for more details. Different link functions may model different regions of the data better.</p>
<p>The choice of distribution family is crucial. Generally for count data, a Poisson distribution is the first port of call, but be prepared to change it (see above). For binary data (e.g. presence/absence or alive/died etc.) the Binomial distribution is usually appropriate. For continuous data, the Normal distribution usually performs well but that leads us straight back to the general linear model. In situations where this skew in the data, a Gamma distribution model may be appropriate. Other distributions can be used other than the Exponential family distributions, but the mathematical foundations of the GLM theory are not as strong.</p>
<p>Another issue is the inclusion of random effects (e.g. blocking) in the model. This leads directly to Generalised Linear Mixed Models (GLMM).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap9.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
